### ISSUE TITLE
DB schema 수정 및 data 추가

### ISSUE THREAD

**Issue by chaewss** [cvs-go/cvs-go-server#13]
## Description
DB schema 수정 및 data 추가

## Todo
- [x] IdClass 수정
- [x] BaseTimeEntity 추가
- [x] event 관련 파일 추가
- [x] review title column 삭제
- [x] schema.sql 수정
- [x] data.sql 수정
