### ISSUE TITLE
api doc 설정

### ISSUE THREAD

**Issue by chaewss** [cvs-go/cvs-go-server#20]
## Description
api-doc 재설정

## Todo
- [x] build.gradle 수정
- [x] api-doc.adoc 파일 이동
- [x] api-doc.html gitignore 추가
- [x] excludePathPatterns에 docs 추가
