### ISSUE TITLE
sql 파일 수정

### ISSUE THREAD

**Issue by chaewss** [cvs-go/cvs-go-server#37]
### 🎯 Issue Overview
sql 파일 수정합니다.

### ✏️ Todo
- [x] schema.sql, data.sql 파일 위치 변경
- [x] schema.sql password varchar(255)로 수정
- [x] schema.sql unique constraint 추가
