### ISSUE TITLE
리뷰 조회 리팩토링

### ISSUE THREAD

**Issue by feel-coding** [cvs-go/cvs-go-server#59]
### 🎯 Issue Overview
리뷰 조회 코드를 리팩토링합니다.

### ✏️ Todo
- [x] 너무 많은 역할을 하는 메소드를 private 메소드로 분리합니다.
- [x] 코드 스타일을 포맷팅합니다.
- [x] 클래스명을 수정합니다.
- [x] 조회만 하는 메소드에 readonly=true 속성을 추가합니다.
- [x] 부족한 테스트 코드를 보강합니다.
