### ISSUE TITLE
상품 필터 조회, 목록 조회, 상세 조회 리팩토링

### ISSUE THREAD

**Issue by chaewss** [cvs-go/cvs-go-server#61]
### 🎯 Issue Overview
상품 목록 조회 API와 상품 상세 조회 API의 코드를 수정합니다.

### ✏️ Todo
- [x] dto 네이밍 변경
- [x] 서비스 코드 가독성을 위한 private 메서드 생성
- [x] api에 사용되는 public 메서드인 경우 Create, Read, Update, Delete로 네이밍 통일
- [x] 키워드 검색 시 띄어쓰기 기준으로 split 후 검색
- [x] 상품 목록 조회 정렬 기준에 좋아요 순 삭제, 리뷰순 추가
- [x] ReadRequestDto에 있는 test를 위한 builder 어노테이션 삭제
- [x] 필터를 적용한 레포지토리 테스트 코드 추가
