### ISSUE TITLE
리뷰 작성/수정시 이미지 업로드 별도 API로 분리

### ISSUE THREAD

**Issue by feel-coding** [cvs-go/cvs-go-server#73]
### 🎯 Issue Overview
이미지 업로드 API를 별도로 분리합니다.

### ✏️ Todo
- [ ] 이미지 업로드 API 추가
- [ ] 리뷰 생성, 수정 API에서 Multipart 파일 대신 이미지 URL을 받도록 수정
- [ ] 테스트 코드 작성
- [ ] 문서 작성
