### ISSUE TITLE
CI/CD 구축

### ISSUE THREAD

**Issue by chaewss** [cvs-go/cvs-go-server#84]
### 🎯 Issue Overview
Github Actions + CodeDeploy를 통한 CI/CD 구축

### ✏️ Todo
- [x] appspec.yml 생성
- [x] deploy.sh 생성
- [x] build.gradle 수정
- [x] github workflow 생성
